# Generated by Django 3.0.5 on 2020-07-03 00:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressnumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('addressstreet', models.CharField(max_length=60)),
                ('addresstown', models.CharField(max_length=60)),
                ('addressstate', models.CharField(max_length=60)),
                ('quickdescrip', models.CharField(max_length=350)),
                ('lockboxcode', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=300)),
                ('proposalorestimatenumber', models.DecimalField(decimal_places=0, max_digits=15)),
                ('clientemailinfo', models.CharField(max_length=400)),
                ('techniciancompletionnotes', models.CharField(max_length=500)),
                ('taskdatecomplete', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('taskdatestart', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('taskcomplete', models.BooleanField(default=False)),
                ('invoicesent', models.BooleanField(default=False)),
                ('client', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
